### ISSUE TITLE
Error when start bot

### ISSUE THREAD

**Issue by bidbiz** [UsergeTeam/Loader#22]
2023-10-08T09:24:51.434270+00:00 app[worker.1]: Process userge:
2023-10-08T09:24:51.434560+00:00 app[worker.1]: Traceback (most recent call last):
2023-10-08T09:24:51.434597+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-10-08T09:24:51.434598+00:00 app[worker.1]:     self.run()
2023-10-08T09:24:51.434598+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-10-08T09:24:51.434598+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2023-10-08T09:24:51.434599+00:00 app[worker.1]:   File "/app/loader/userge/main.py", line 9, in run
2023-10-08T09:24:51.434600+00:00 app[worker.1]:     getattr(getattr(import_module("userge.main"), 'userge'), 'begin')()
2023-10-08T09:24:51.434608+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 332, in begin
2023-10-08T09:24:51.434608+00:00 app[worker.1]:     self.loop.run_until_complete(self.start())
2023-10-08T09:24:51.434608+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-10-08T09:24:51.434609+00:00 app[worker.1]:     return future.result()
2023-10-08T09:24:51.434610+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 297, in start
2023-10-08T09:24:51.434610+00:00 app[worker.1]:     await super().start()
2023-10-08T09:24:51.434610+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 221, in start
2023-10-08T09:24:51.434611+00:00 app[worker.1]:     await super().start()
2023-10-08T09:24:51.434612+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
2023-10-08T09:24:51.434612+00:00 app[worker.1]:     is_authorized = await self.connect()
2023-10-08T09:24:51.434613+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
2023-10-08T09:24:51.434618+00:00 app[worker.1]:     await self.session.start()
2023-10-08T09:24:51.434619+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 142, in start
2023-10-08T09:24:51.434619+00:00 app[worker.1]:     raise e
2023-10-08T09:24:51.434619+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 109, in start
2023-10-08T09:24:51.434619+00:00 app[worker.1]:     await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
2023-10-08T09:24:51.434620+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 333, in send
2023-10-08T09:24:51.434620+00:00 app[worker.1]:     raise BadMsgNotification(result.error_code)
2023-10-08T09:24:51.434633+00:00 app[worker.1]: pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Comment by onurmercury** [comment]
Python 3.10 doesn't work well with userge, try my loader fork

https://github.com/onurmercury/userge-loader

**Comment by bidbiz** [comment]
> Python 3.10 doesn't work well with userge, try my loader fork
> 
> https://github.com/onurmercury/userge-loader

Still with the same error

**Comment by onurmercury** [comment]
> > Python 3.10 doesn't work well with userge, try my loader fork
> > https://github.com/onurmercury/userge-loader
> 
> Still with the same error

Are you using the docker image or just downloaded the repo and tried to run the `run` script?

**Comment by bidbiz** [comment]
> > > Python 3.10 doesn't work well with userge, try my loader fork
> > > https://github.com/onurmercury/userge-loader
> > 
> > 
> > Still with the same error
> 
> Are you using the docker image or just downloaded the repo and tried to run the `run` script?

Using docker, docker compose...
